title: "널빈's 학습 공간"
email: "dhyunchoi@kyonggi.ac.kr"
description: "CS 학습 내용을 기록하는 NullBins's 기술 블로그입니다."
url: "https://nullbins.github.io"
baseurl: ""
timezone: Asia/Seoul
lang: ko

markdown: kramdown
highlighter: rouge