title: "널빈의 학습 공간"
email: "dhyunchoi@kyonggi.ac.kr"
description: "| 널빈의 학습기록 공간 | NullBins's Learning space"
url: "https://nullbins.github.io"
timezone: Asia/Seoul

markdown: kramdown
highlighter: rouge